### ISSUE TITLE
Endpoint for mass import of customers

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-betaling-backend#56]
Add `POST` endpoint for the frontend to upload an Excel spreadsheet containing:
- Navn
- VIS ID (`/elevforhold/systemid`)
- Klasse

According to the format described here: https://inschool.zendesk.com/hc/no/articles/360032717911-Hvordan-skrive-ut-klasselister

**Comment by OlaStalberg** [comment]
Added in #60
